[package]
name = "markdown-renderer"
authors.workspace = true
edition.workspace = true
version.workspace = true
description.workspace = true

[dependencies]
thiserror.workspace = true
anyhow.workspace = true
